//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBackend.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ProjectBackend.ServiceReference1.HelloWorldResponse HelloWorld(ProjectBackend.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBackend.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ProjectBackend.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name courses from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveCharWebService", ReplyAction="*")]
        ProjectBackend.ServiceReference1.RemoveCharWebServiceResponse RemoveCharWebService(ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveCharWebService", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBackend.ServiceReference1.RemoveCharWebServiceResponse> RemoveCharWebServiceAsync(ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBackend.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProjectBackend.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBackend.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProjectBackend.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveCharWebServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveCharWebService", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBackend.ServiceReference1.RemoveCharWebServiceRequestBody Body;
        
        public RemoveCharWebServiceRequest() {
        }
        
        public RemoveCharWebServiceRequest(ProjectBackend.ServiceReference1.RemoveCharWebServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveCharWebServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string courses;
        
        public RemoveCharWebServiceRequestBody() {
        }
        
        public RemoveCharWebServiceRequestBody(string courses) {
            this.courses = courses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveCharWebServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveCharWebServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBackend.ServiceReference1.RemoveCharWebServiceResponseBody Body;
        
        public RemoveCharWebServiceResponse() {
        }
        
        public RemoveCharWebServiceResponse(ProjectBackend.ServiceReference1.RemoveCharWebServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveCharWebServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemoveCharWebServiceResult;
        
        public RemoveCharWebServiceResponseBody() {
        }
        
        public RemoveCharWebServiceResponseBody(string RemoveCharWebServiceResult) {
            this.RemoveCharWebServiceResult = RemoveCharWebServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ProjectBackend.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ProjectBackend.ServiceReference1.WebService1Soap>, ProjectBackend.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBackend.ServiceReference1.HelloWorldResponse ProjectBackend.ServiceReference1.WebService1Soap.HelloWorld(ProjectBackend.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProjectBackend.ServiceReference1.HelloWorldRequest inValue = new ProjectBackend.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProjectBackend.ServiceReference1.HelloWorldRequestBody();
            ProjectBackend.ServiceReference1.HelloWorldResponse retVal = ((ProjectBackend.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBackend.ServiceReference1.HelloWorldResponse> ProjectBackend.ServiceReference1.WebService1Soap.HelloWorldAsync(ProjectBackend.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBackend.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ProjectBackend.ServiceReference1.HelloWorldRequest inValue = new ProjectBackend.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProjectBackend.ServiceReference1.HelloWorldRequestBody();
            return ((ProjectBackend.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBackend.ServiceReference1.RemoveCharWebServiceResponse ProjectBackend.ServiceReference1.WebService1Soap.RemoveCharWebService(ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest request) {
            return base.Channel.RemoveCharWebService(request);
        }
        
        public string RemoveCharWebService(string courses) {
            ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest inValue = new ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest();
            inValue.Body = new ProjectBackend.ServiceReference1.RemoveCharWebServiceRequestBody();
            inValue.Body.courses = courses;
            ProjectBackend.ServiceReference1.RemoveCharWebServiceResponse retVal = ((ProjectBackend.ServiceReference1.WebService1Soap)(this)).RemoveCharWebService(inValue);
            return retVal.Body.RemoveCharWebServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBackend.ServiceReference1.RemoveCharWebServiceResponse> ProjectBackend.ServiceReference1.WebService1Soap.RemoveCharWebServiceAsync(ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest request) {
            return base.Channel.RemoveCharWebServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBackend.ServiceReference1.RemoveCharWebServiceResponse> RemoveCharWebServiceAsync(string courses) {
            ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest inValue = new ProjectBackend.ServiceReference1.RemoveCharWebServiceRequest();
            inValue.Body = new ProjectBackend.ServiceReference1.RemoveCharWebServiceRequestBody();
            inValue.Body.courses = courses;
            return ((ProjectBackend.ServiceReference1.WebService1Soap)(this)).RemoveCharWebServiceAsync(inValue);
        }
    }
}
